### ISSUE TITLE
Add app framework

### ISSUE THREAD

**Issue by br3ndonland** [growwithgooglema/mbtaccess#33]
# Add app framework

## Current behavior

The app is coming along very nicely. Thanks @AbdouSeck and @jethridge13  for the great commits lately. In addition to the upcoming features we plan to implement, we should think more about performance.

Right now, our app involves offline Python code used to retrieve the university data, JavaScript to generate the map and make distance calculations, HTML with styling from Bootstrap, and hosting with GitHub Pages. One issue with this structure is that performance will be highly variable depending on the operating system and browser. On my laptop (MacBook Air, macOS High Sierra 10.13.4, Firefox 59.0.2), the [current app](https://growwithgooglema.github.io/gwg-mbta/index.html) only takes a few seconds to drop pins for nearby stops. On my mobile device (Google Pixel XL, Android 8.1.0, Firefox 59.0.2), it takes 30-40 seconds.

## Suggested behavior

We should optimize app performance for mobile devices, where it will be most useful. I would suggest using a JavaScript framework to speed up the app. I'm starting to learn [Knockout](http://knockoutjs.com/) for a Udacity project, and it might be a good choice for our gwg-mbta app also.

Front-end frameworks like Knockout or Angular can be [flexibly combined](https://stackoverflow.com/questions/11522151/typical-angularjs-workflow-and-project-structure-with-python-flask) with back-ends like Flask. We can think about formatting the Python code for Flask and then Dockerizing the app so that no offline code is needed. We could also try to do everything with JavaScript instead of Python, so that the back-end is simply APIs (the "[JAMstack](https://jamstack.org/)" approach). If anyone wants to work on Flask or Python to JS conversion, I suggest opening a separate issue.

I am happy to build in a framework. It will probably be a few weeks until I can get to it. The Udacity project I'm working on is similar, and I want to make sure I code it independently and get the project accepted before I work more here. If anyone else wants to chip in before I do, just drop a message here.

**Comment by AbdouSeck** [comment]
There are two key reasons why the app is slow:

1. The usage of geolocation through the [`navigator.geolocation`](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation) takes a considerable amount of time. This has got nothing to do with the code, but rather a combination of hardware, location and other factors. We may just have to speak to people who've successfully implemented apps with this feature for some tips.

2. We're dealing with a lot of MBTA stops here; 8360 stops to be precise. So, the combination of fetching both the user's location and the MBTA stops can take a fair bit of time.

To my understanding, these issues will not be solved with a python or javascript backend, since we're reliant on API's we have very little control on. For now, at least, the best way to speed things up is to figure out a way to get the user's location or the searched location much more quickly. In fact, the app is pretty fast once both the user's location and the MBTA stops have been fetched. Subsequent lookups are very fast.

We're due for another get-together, I think. That could help us figure this one out.

**Comment by br3ndonland** [comment]
Thanks for your perspective @AbdouSeck . Another meetup would be great!

**Comment by jethridge13** [comment]
I agree, another meetup would be awesome! We could advertise the project in the new Slack channels too, see if more people would like to learn about what we've done so far.

**Comment by br3ndonland** [comment]
We revisited this in our [meeting on July 15 2018](https://github.com/orgs/growwithgooglema/teams/mbtaccess/discussions/6).

This issue relates to two topics:

1. **Speed**
2. **Templating**

@AbdouSeck has agreed to take the lead on this. He plans to build out the back-end for speed, and then add templating for the app page layouts.

I'm going to close this issue, and open new issues for more specific next steps.
